apiVersion: v1
data:
  .env: |
    TOKEN_HOUR_LIFESPAN=24
    API_SECRET=826db23b89851d75641b142465b631cc6ddf7aebf35c747d8bd7add1eec608d4
kind: ConfigMap
metadata:
  name: laas-config-5t85ct2m9g
---
apiVersion: v1
data:
  POSTGRES_DB: fossology
  POSTGRES_PASSWORD: fossy
  POSTGRES_USER: fossy
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: laas-postgres
  name: postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: laas
  name: laas
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: laas
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: laas-postgres
  name: postgres-service
spec:
  ports:
  - port: 5432
  selector:
    app.kubernetes.io/name: laas-postgres
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: laas-postgres
  name: postgres-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: laas
  name: laas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: laas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: laas
    spec:
      containers:
      - args:
        - -dbhost
        - laas-postgres-service.licensedb.svc.cluster.local
        - -populatedb
        - "false"
        image: ko://github.com/fossology/LicenseDb/cmd/laas
        name: laas
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - configMap:
          name: laas-config-5t85ct2m9g
        name: laas-config-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  app.kubernetes.io/name: laas-postgres
  name: postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: laas-postgres
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: postgres-secret
        image: postgres:14
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgres-volume-claim
