apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: laas-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: laas-postgres
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: laas-postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
